

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: booking-service
            uri: lb://BOOKING-SERVICE
            predicates:
              - Path=/book/**
          - id: payment-service
            uri: lb://PAYMENT-SERVICE
            predicates:
              - Path=/payment/**