eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sksingh1993/config-server



